### PR TITLE
DOCS Rewrite docs for LDAP and AD, removing reference to SAML module

### LINKED ISSUE #1: Update documentation to ensure it's relevant for LDAP with no references to SAML

### PR DESCRIPTION
**Pull request by robbieaverill**
This also references some code and changes that are made in #5 

Resolves #1

### CODE REVIEW

**Comment by robbieaverill** [comment]
cc @ichaber

**Comment by ichaber** [comment]
Looks good to me only minor changes (as noted) would be preferential.

**Comment by robbieaverill** [comment]
@ichaber are the changes you're referring to on https://github.com/silverstripe/silverstripe-ldap/pull/5? Any suggestions for the docs?

**Comment by ichaber** [comment]
Sorry, the changes were referring to #5. The docs look fine to me.

**Comment by robbieaverill** [comment]
Self merging with @ichaber's approval

**Pull request merged**
